name: dotenv
version: 0.1.0
description: Load environment variables from a `.env` file.
author: mockturtl
#homepage: https://mockturtl.github.io/pico_log
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  logging: '^0.9.0'
  pico_log:
    path: ../pico_log
dev_dependencies:
  unittest: any
